In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [ ]:
# Test for Apple Silicon
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

In [ ]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

In [ ]:
## Tensors
### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar
scalar.item()

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim
vector.shape

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
#random_image_size_tensor
#random_image_size_tensor, torch.rand

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.arange(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

In [ ]:
# Create a tensor of all zeros of size (224, 224, 3)
ones = torch.ones(size=(224, 224, 3))
ones, ones.dtype

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten


In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

Stuff got deleted - idk what happend

In [ ]:
tensor = torch.tensor([1, 2, 3])

# Print tensor + 10
print("Add 10 to tensor:", tensor + 10)
print()

# Print tensor * 10
print("Multiply tensor by 10:", tensor * 10)
print()

# Print the original tensor (it hasn't changed yet)
print("Original tensor:", tensor)
print()

# Subtract 10 and reassign to tensor
tensor = tensor - 10
print("Tensor after subtracting 10:", tensor)
print()

# Add 10 and reassign to tensor
tensor = tensor + 10
print("Tensor after adding 10:", tensor)
print()

# Use torch.multiply function to multiply tensor by 10
print("Multiply tensor by 10 using torch.multiply: or torch.mul", torch.mul(tensor, 10))
print()

# Print the original tensor again (it hasn't changed)
print("Original tensor remains unchanged:", tensor)
print()

# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


# Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])

# Print the shape of the tensor
print("Shape of the tensor:", tensor.shape)
print()

# Element-wise multiplication (multiplying each element by itself)
print("Element-wise matrix multiplication (tensor * tensor):", tensor * tensor)
print()

# Matrix multiplication (using torch.matmul())
print("Matrix multiplication (torch.matmul(tensor, tensor)):", torch.matmul(tensor, tensor))
print()

# Matrix multiplication using the '@' symbol (not recommended)
print("Matrix multiplication using '@' symbol (tensor @ tensor):", tensor @ tensor)
print()

# Manual matrix multiplication by hand using a for loop (inefficient)
print("Manual matrix multiplication by hand (for loop):")
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print("Result:", value)
print()

# Time comparison: manual matrix multiplication
import time
start_time = time.time()
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print("Manual matrix multiplication took:", time.time() - start_time)

# Time comparison: using torch.matmul()
start_time = time.time()
torch.matmul(tensor, tensor)
print("torch.matmul() matrix multiplication took:", time.time() - start_time)


# Initialize vars for mm

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error) - both are 2,3

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # Fixes error since both inner axis are the same

In [ ]:
print(tensor_A)
print()
print(tensor_B)
print()
print()
print(tensor_A)
print(tensor_B.T)

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x
x.float

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"x datatype before {x.dtype}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"x datatype with alteration {x.type(torch.float32).dtype}")
print(f"Sum: {x.sum()}")

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}") # 1 dimensional

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.) # the #. specifiys a floating point
print(f"{tensor} , {tensor.dtype}")
x = torch.arange(10, 100, 10)
print(f"{x} , {x.dtype}")
print()
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16) # another way to specify dtype=torch.float16 if not a 1d array
print(f"{tensor_float16}")
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(f"{tensor_int8}")


In [ ]:
# Create a tensor
x = torch.arange(1., 8.)
print(f"{x, x.shape}")
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
print(f"{x_reshaped, x_reshaped.shape}")

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

print()

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

#Indexing (selecting data from tensors)

In [ ]:
# Create a tensor 
x = torch.arange(1, 10).reshape(1, 3, 3)
print(f"{x}, {x.shape}")

print()

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
print(f"{x[:, 0]}")

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(f"{x[:, :, 1]}")

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(f"{x[:, 1, 1]}")

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(f"{x[0, 0, :]}") # same as x[0][0]

# PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

In [76]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

In [92]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
print(RANDOM_SEED)
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

42
Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPU

In [96]:
print(torch.cuda.is_available())
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

False


'cpu'

In [99]:
# Check for Apple Silicon GPU
print(torch.backends.mps.is_available()) # Note this will print false if you're not running on a Mac
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

True


'mps'

## Simplified

In [102]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

print(device)

mps
