In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1


In [ ]:
# Test for Apple Silicon
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [26]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [3]:
## Tensors
### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar
scalar.item()

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim
vector.shape

In [6]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [7]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [8]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1090, 0.9310, 0.9957, 0.4504],
         [0.4558, 0.3078, 0.5887, 0.2360],
         [0.4670, 0.1251, 0.1497, 0.0182]]),
 torch.float32)

In [7]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
#random_image_size_tensor
#random_image_size_tensor, torch.rand

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.arange(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

In [6]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

In [ ]:
# Create a tensor of all zeros of size (224, 224, 3)
ones = torch.ones(size=(224, 224, 3))
ones, ones.dtype

In [5]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Stuff got deleted - idk what happend

In [ ]:
tensor = torch.tensor([1, 2, 3])

# Print tensor + 10
print("Add 10 to tensor:", tensor + 10)
print()

# Print tensor * 10
print("Multiply tensor by 10:", tensor * 10)
print()

# Print the original tensor (it hasn't changed yet)
print("Original tensor:", tensor)
print()

# Subtract 10 and reassign to tensor
tensor = tensor - 10
print("Tensor after subtracting 10:", tensor)
print()

# Add 10 and reassign to tensor
tensor = tensor + 10
print("Tensor after adding 10:", tensor)
print()

# Use torch.multiply function to multiply tensor by 10
print("Multiply tensor by 10 using torch.multiply: or torch.mul", torch.mul(tensor, 10))
print()

# Print the original tensor again (it hasn't changed)
print("Original tensor remains unchanged:", tensor)
print()

# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)


# Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])

# Print the shape of the tensor
print("Shape of the tensor:", tensor.shape)
print()

# Element-wise multiplication (multiplying each element by itself)
print("Element-wise matrix multiplication (tensor * tensor):", tensor * tensor)
print()

# Matrix multiplication (using torch.matmul())
print("Matrix multiplication (torch.matmul(tensor, tensor)):", torch.matmul(tensor, tensor))
print()

# Matrix multiplication using the '@' symbol (not recommended)
print("Matrix multiplication using '@' symbol (tensor @ tensor):", tensor @ tensor)
print()

# Manual matrix multiplication by hand using a for loop (inefficient)
print("Manual matrix multiplication by hand (for loop):")
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print("Result:", value)
print()

# Time comparison: manual matrix multiplication
import time
start_time = time.time()
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print("Manual matrix multiplication took:", time.time() - start_time)

# Time comparison: using torch.matmul()
start_time = time.time()
torch.matmul(tensor, tensor)
print("torch.matmul() matrix multiplication took:", time.time() - start_time)


# Initialize vars for mm

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error) - both are 2,3

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # Fixes error since both inner axis are the same

In [ ]:
print(tensor_A)
print()
print(tensor_B)
print()
print()
print(tensor_A)
print(tensor_B.T)

In [42]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [10]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [18]:
# Create a tensor
x = torch.arange(0, 100, 10)
x
x.float

<function Tensor.float>

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"x datatype before {x.dtype}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"x datatype with alteration {x.type(torch.float32).dtype}")
print(f"Sum: {x.sum()}")

In [24]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}") # 1 dimensional

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [41]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.) # the #. specifiys a floating point
print(f"{tensor} , {tensor.dtype}")
x = torch.arange(10, 100, 10)
print(f"{x} , {x.dtype}")
print()
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16) # another way to specify dtype=torch.float16 if not a 1d array
print(f"{tensor_float16}")
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(f"{tensor_int8}")


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]) , torch.float32
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]) , torch.int64

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


In [50]:
# Create a tensor
x = torch.arange(1., 8.)
print(f"{x, x.shape}")
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
print(f"{x_reshaped, x_reshaped.shape}")

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))
(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))
